language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
env:
    - DJANGO_VERSION=1.8.3 FLASK_VERSION=0.10.1 JINJA2_VERSION=2.7.3
install:
    - pip install -q coveralls jinja2==$JINJA2_VERSION flask==$FLASK_VERSION django==$DJANGO_VERSION
    - python setup.py -q install
script:
    - coverage run --source=blocky setup.py test
after_success:
    - coveralls
